--- 
abstract: ~
author: 
  - Maxim Grigoriev (FNAL), maxim_at_fnal_dot_gov
distribution_type: module
generated_by: Module::Install version 0.68
license: Fermitools
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-RelaxNG-Compact-PXB
no_index: 
  directory: 
    - t
    - inc
    - t
requires: 
  Class::Accessor: 0
  Class::Fields: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Path: 0
  FindBin: 0
  FreezeThaw: 0
  Log::Log4perl: 0
  POD::Credentials: 0.03
  Perl::Critic: 0
  Perl::Tidy: 0
  Readonly: 0
  Scalar::Util: 0
  Test::Harness: 0
  Test::More: 0
  XML::LibXML: 1.61
  XML::LibXML::Common: 0.13
  XML::NamespaceSupport: 1
  base: 0
  fields: 0
  perl: 5.6.1
  version: 0
version: 0.03
