--- 
name: XML-RelaxNG-Compact-PXB
abstract: XML RelaxNG Compact data binding 
version: 0.04
distribution_type: module
license: Fermitools
installdirs: site

requires: 
  Class::Accessor: 0
  Class::Fields: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Path: 0
  FindBin: 0
  FreezeThaw: 0
  Log::Log4perl: 0
  POD::Credentials: 0.04
  Perl::Critic: 0
  Perl::Tidy: 0
  Readonly: 0
  Scalar::Util: 0
  Test::Harness: 0
  Test::More: 0
  XML::LibXML: 1.61
  XML::LibXML::Common: 0.13
  XML::NamespaceSupport: 1 
  XML::LibXML::XPathContext: 0.04
  fields: 0
  perl: 5.6.1
  version: 0

